version: 0.2
phases:
  build:
    commands:
     - node test.js
  post_build:
    commands:
     - echo Build completed on `date`
     - 'aws sns publish --topic-arn $SNS_TOPIC --message "{\"buildId\": \"$CODEBUILD_BUILD_ID\"}"'
