version: 0.2

env:
  variables:
    TEST_VAR: "hola mundo"

phases:
  install:
    commands:
     - git-auth
     - git clone git@github.com:bcilabs/mach-api.git
     - cd mach-api
     - git submodule update --init
     - ./compose.sh start -b -d
     - docker images
