version: 0.2
phases:
  install:
    commands:
     - decrypt-key
     - git clone git@github.com:bcilabs/mach-api.git
     - cd mach-api
  pre_build:
    commands:
     - eval $(aws ecr get-login --no-include-email --region us-east-1)
     - yarn
  build:
    commands:
     - yarn lint
     - yarn test
     - yarn build
     - docker build -t hsalazr/test-build .
  post_build:
    commands:
     - echo Build completed on `date`
     - 'aws sns publish --topic-arn $SNS_TOPIC --message "{\"buildId\": \"$CODEBUILD_BUILD_ID\"}"'
     - docker tag hsalazr/test-build:latest 425782179927.dkr.ecr.us-east-1.amazonaws.com/hsalazr/test-build:latest
     - docker push 425782179927.dkr.ecr.us-east-1.amazonaws.com/hsalazr/test-build:latest
