version: 0.2
phases:
  build:
    commands:
     - decrypt-key
     - git clone git@github.com:bcilabs/mach-api.git
     - cd mach-api
     - git submodule update --init
artifacts:
  files:
    - ./mach-api/*
