version: 0.2
phases:
  install:
    commands:
     - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=vfs&
     - timeout -t 15 sh -c "until docker info; do echo .; sleep 1; done"
     - decrypt-key
     - git clone git@github.com:bcilabs/mach-api.git
     - cd mach-api
  pre_build:
    commands:
     - $(aws ecr get-login --no-include-email --region us-east-1)
     - yarn
  build:
    commands:
     - yarn lint
     - yarn test
     - yarn build
     - docker build -t hsalazr/test-build .
  post_build:
    commands:
     - echo Build completed on `date`
     - 'aws sns publish --topic-arn $SNS_TOPIC --message "{\"buildId\": \"$CODEBUILD_BUILD_ID\"}"'
     - docker tag hsalazr/test-build:latest 425782179927.dkr.ecr.us-east-1.amazonaws.com/hsalazr/test-build:latest
     - docker push 425782179927.dkr.ecr.us-east-1.amazonaws.com/hsalazr/test-build:latest
