version: 0.2
phases:
  install:
    commands:
     - decrypt-key
     - git clone git@github.com:bcilabs/mach-api.git
     - cd mach-api
     - git submodule update --init
     - ./root/.yarn/bin/yarn
  pre_build:
    comands:
    - ./root/.yarn/bin/yarn lint
    - ./root/.yarn/bin/yarn test
    - ./root/.yarn/bin/yarn coverage
  build:
    commands:     
     - yarn build
  post_build:
    commands:
     - echo Build completed on `date`
     - 'aws sns publish --topic-arn arn:aws:sns:us-east-1:425782179927:test-build --message "{\"buildId\": \"$CODEBUILD_BUILD_ID\"}"'
artifacts:
  files:
    - ./mach-api/*
