version: 0.2
phases:
  install:
    commands:
     - decrypt-key
     - git clone git@github.com:bcilabs/mach-api.git
     - cd mach-api
     - git submodule update --init
  pre_build:
    commands:
     - yarn
  build:
    commands:
     - yarn lint
     - yarn test
     - yarn coverage
     - yarn build
  post_build:
    commands:
     - echo Build completed on `date`
     - 'aws sns publish --topic-arn $SNS_TOPIC --message "{\"buildId\": \"$CODEBUILD_BUILD_ID\"}"'
