version: 0.2
phases:
  install:
    commands:
     - git-auth
     - cat ~/.ssh/github.com
     - git clone git@github.com:bcilabs/mach-api.git
     - cd mach-api
     - git submodule update --init
     - ./compose.sh start -b -d
     - docker images
